### ISSUE TITLE
EVENT REQUEST

### ISSUE THREAD

**Issue by SillySoon** [Maticzpl/MoreHazards#3]
**Turning all lights OFF (so that flashlights have a need to exist) + Cassie Announcement.**
_btw i dont know github that much so i put it in here_

**config file template:**
```
# Light System breakdown module - a rare event that will disable all Lights in facility for a few seconds.
  light_system_breakdown:
    enabled: true
    # The cooldown and duration of this event.
    light_system_breakdown_timing:
    # Min Duration of the event - default: 30
      min_duration: 30
      # Max Duration of the event - default: 45
      max_duration: 45
      # Min Cooldown between calling this event - default: 300
      min_cooldown: 300
      # Max Cooldown between calling this event - default: 450
      max_cooldown: 450
    # Is the mesage below enabled
    use_cassie_message: true
    # The message that will play on light system breakdown
    cassie_message_on_breakdown:
    # Cassie Message Text
      text: ''
      # Cassie Message Glitch Chance (0-100)
      glitches: 10
      # Cassie Message Jam Chance (0-100)
      jams: 10
```
